<?php

declare(strict_types=1);

namespace Tests\Unit\Modules\Delivery\Models;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class AssessmentSessionModelTest extends TestCase
{
    use RefreshDatabase;

    public function test_it_has_uuid(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_it_belongs_to_organization(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_it_has_relations(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
