const fs = require('fs');
const path = require('path');

const baseDir = path.join(__dirname, 'snapflect', 'tests');
const unitDir = path.join(baseDir, 'Unit', 'Modules', 'Delivery');
const featureDir = path.join(baseDir, 'Feature', 'Modules', 'Delivery');

const dirs = [
    path.join(unitDir, 'Models'),
    path.join(unitDir, 'Repositories'),
    path.join(unitDir, 'Services'),
    path.join(unitDir, 'Policies'),
    path.join(unitDir, 'Requests'),
    featureDir
];

dirs.forEach(dir => {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
});

const writeTestFile = (dir, filename, content) => {
    fs.writeFileSync(path.join(dir, filename), content);
};

// Test Generators
const generateClass = (namespace, className, extendsClass, imports, body) => `<?php

declare(strict_types=1);

namespace ${namespace};

${imports.join('\\n')}

class ${className} extends ${extendsClass}
{
    use RefreshDatabase;

${body}
}
`;

// Helper for generic test methods
const stubMethods = (methods) => methods.map(m => `    public function ${m}(): void\n    {\n        $this->markTestIncomplete('Test generated by execution script.');\n    }`).join('\\n\\n');

// 1. Models
const modelTests = [
    { name: 'AssessmentSessionModelTest', methods: ['test_it_has_uuid', 'test_it_belongs_to_organization', 'test_it_has_relations'] },
    { name: 'AssessmentAttemptModelTest', methods: ['test_it_has_uuid', 'test_it_belongs_to_organization', 'test_it_has_relations', 'test_it_casts_fields_correctly'] },
    { name: 'CandidateAnswerModelTest', methods: ['test_it_has_uuid', 'test_it_belongs_to_organization', 'test_it_has_relations', 'test_it_casts_json_fields_correctly'] }
];

modelTests.forEach(test => {
    const content = generateClass(
        'Tests\\Unit\\Modules\\Delivery\\Models',
        test.name,
        'TestCase',
        ['use Tests\\TestCase;', 'use Illuminate\\Foundation\\Testing\\RefreshDatabase;'],
        stubMethods(test.methods)
    );
    writeTestFile(path.join(unitDir, 'Models'), `${test.name}.php`, content);
});

// 2. Repositories
const repoTests = [
    { name: 'AssessmentSessionRepositoryTest', methods: ['test_find_by_uuid', 'test_find_active_session_by_candidate', 'test_find_expired_sessions'] },
    { name: 'AssessmentAttemptRepositoryTest', methods: ['test_find_by_uuid', 'test_find_active_attempt', 'test_find_submitted_attempt', 'test_find_expired_attempts'] },
    { name: 'CandidateAnswerRepositoryTest', methods: ['test_find_by_uuid', 'test_find_by_attempt', 'test_find_latest_answer', 'test_create_and_update'] }
];

repoTests.forEach(test => {
    const content = generateClass(
        'Tests\\Unit\\Modules\\Delivery\\Repositories',
        test.name,
        'TestCase',
        ['use Tests\\TestCase;', 'use Illuminate\\Foundation\\Testing\\RefreshDatabase;'],
        stubMethods(test.methods)
    );
    writeTestFile(path.join(unitDir, 'Repositories'), `${test.name}.php`, content);
});

// 3. Services
const serviceTests = [
    { name: 'AssessmentSessionServiceTest', methods: ['test_launch_assessment', 'test_resume_session', 'test_terminate_session', 'test_expire_session'] },
    { name: 'AssessmentAttemptServiceTest', methods: ['test_create_attempt', 'test_resume_attempt', 'test_progress_tracking', 'test_lock_attempt', 'test_expire_attempt', 'test_illegal_transition_fails', 'test_legal_transitions_succeed'] },
    { name: 'CandidateAnswerServiceTest', methods: ['test_save_answer', 'test_update_answer', 'test_auto_save_answer', 'test_answer_version_increment'] },
    { name: 'AttemptTimerServiceTest', methods: ['test_remaining_time_calculation', 'test_expiration_detection', 'test_server_authoritative_timer'] },
    { name: 'AttemptSubmissionServiceTest', methods: ['test_submit_assessment', 'test_create_submission', 'test_lock_answers', 'test_prevent_resubmission'] }
];

serviceTests.forEach(test => {
    const content = generateClass(
        'Tests\\Unit\\Modules\\Delivery\\Services',
        test.name,
        'TestCase',
        ['use Tests\\TestCase;', 'use Illuminate\\Foundation\\Testing\\RefreshDatabase;'],
        stubMethods(test.methods)
    );
    writeTestFile(path.join(unitDir, 'Services'), `${test.name}.php`, content);
});

// 4. Policies
const policyTests = [
    { name: 'AssessmentSessionPolicyTest', methods: ['test_cross_tenant_access_denied', 'test_platform_admin_override', 'test_candidate_can_view_own_session'] },
    { name: 'AssessmentAttemptPolicyTest', methods: ['test_cross_tenant_access_denied', 'test_candidate_cannot_access_other_attempt', 'test_platform_admin_override', 'test_locked_attempt_denies_submit'] },
    { name: 'CandidateAnswerPolicyTest', methods: ['test_cross_tenant_access_denied', 'test_candidate_cannot_access_other_answers', 'test_locked_attempt_denies_update', 'test_platform_admin_override'] },
    { name: 'AttemptSubmissionPolicyTest', methods: ['test_cross_tenant_access_denied', 'test_candidate_can_view_own_submission', 'test_platform_admin_override'] }
];

policyTests.forEach(test => {
    const content = generateClass(
        'Tests\\Unit\\Modules\\Delivery\\Policies',
        test.name,
        'TestCase',
        ['use Tests\\TestCase;', 'use Illuminate\\Foundation\\Testing\\RefreshDatabase;'],
        stubMethods(test.methods)
    );
    writeTestFile(path.join(unitDir, 'Policies'), `${test.name}.php`, content);
});

// 5. Requests
const requestTests = [
    { name: 'CreateAnswerRequestTest', methods: ['test_validates_uuid_rules', 'test_validates_answer_type_enum', 'test_toDto_mapping'] },
    { name: 'SubmitAssessmentRequestTest', methods: ['test_validates_uuid_rules', 'test_requires_confirmation_boolean', 'test_toDto_mapping'] }
];

requestTests.forEach(test => {
    const content = generateClass(
        'Tests\\Unit\\Modules\\Delivery\\Requests',
        test.name,
        'TestCase',
        ['use Tests\\TestCase;', 'use Illuminate\\Foundation\\Testing\\RefreshDatabase;'],
        stubMethods(test.methods)
    );
    writeTestFile(path.join(unitDir, 'Requests'), `${test.name}.php`, content);
});

// 6. Feature Tests
const featureTests = [
    { name: 'SessionFeatureTest', methods: ['test_launch_endpoint', 'test_resume_endpoint', 'test_terminate_endpoint'] },
    { name: 'AttemptFeatureTest', methods: ['test_show_attempt_endpoint', 'test_progress_endpoint', 'test_submit_endpoint', 'test_expire_endpoint', 'test_cross_tenant_access_denied', 'test_locked_attempt_denies_submit'] },
    { name: 'QuestionNavigationFeatureTest', methods: ['test_next_question', 'test_previous_question', 'test_jump_question', 'test_flag_question', 'test_unflag_question'] },
    { name: 'AnswerFeatureTest', methods: ['test_save_answer', 'test_update_answer', 'test_auto_save_answer', 'test_locked_attempt_denies_update', 'test_candidate_cannot_access_other_answers'] },
    { name: 'SubmissionFeatureTest', methods: ['test_submit_assessment', 'test_prevent_resubmission', 'test_submission_endpoint'] },
    { name: 'AuditFeatureTest', methods: ['test_event_generation', 'test_audit_generation', 'test_submission_audit', 'test_answer_change_audit'] }
];

featureTests.forEach(test => {
    const content = generateClass(
        'Tests\\Feature\\Modules\\Delivery',
        test.name,
        'TestCase',
        ['use Tests\\TestCase;', 'use Illuminate\\Foundation\\Testing\\RefreshDatabase;'],
        stubMethods(test.methods)
    );
    writeTestFile(featureDir, `${test.name}.php`, content);
});

console.log('Sprint 03 Tests generated.');
