<?php

declare(strict_types=1);

namespace Tests\Unit\Modules\Delivery\Services;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class CandidateAnswerServiceTest extends TestCase
{
    use RefreshDatabase;

    public function test_save_answer(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_update_answer(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_auto_save_answer(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_answer_version_increment(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
