<?php

declare(strict_types=1);

namespace Tests\Unit\Modules\Delivery\Services;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class AttemptSubmissionServiceTest extends TestCase
{
    use RefreshDatabase;

    public function test_submit_assessment(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_create_submission(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_lock_answers(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_prevent_resubmission(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
