<?php

declare(strict_types=1);

namespace Tests\Unit\Modules\Delivery\Repositories;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class AssessmentSessionRepositoryTest extends TestCase
{
    use RefreshDatabase;

    public function test_find_by_uuid(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_find_active_session_by_candidate(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_find_expired_sessions(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
