<?php

declare(strict_types=1);

namespace Tests\Unit\Modules\Delivery\Repositories;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class CandidateAnswerRepositoryTest extends TestCase
{
    use RefreshDatabase;

    public function test_find_by_uuid(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_find_by_attempt(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_find_latest_answer(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_create_and_update(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
