<?php

declare(strict_types=1);

namespace Tests\Feature\Modules\Delivery;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class SessionFeatureTest extends TestCase
{
    use RefreshDatabase;

    public function test_launch_endpoint(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_resume_endpoint(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_terminate_endpoint(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
