<?php

declare(strict_types=1);

namespace Tests\Feature\Modules\Delivery;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class QuestionNavigationFeatureTest extends TestCase
{
    use RefreshDatabase;

    public function test_next_question(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_previous_question(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_jump_question(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_flag_question(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_unflag_question(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
