<?php

declare(strict_types=1);

namespace Tests\Feature\Modules\Delivery;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class AttemptFeatureTest extends TestCase
{
    use RefreshDatabase;

    public function test_show_attempt_endpoint(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_progress_endpoint(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_submit_endpoint(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_expire_endpoint(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_cross_tenant_access_denied(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_locked_attempt_denies_submit(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
