<?php

declare(strict_types=1);

namespace Tests\Unit\Modules\Delivery\Requests;

use Tests\TestCase;\nuse Illuminate\Foundation\Testing\RefreshDatabase;

class CreateAnswerRequestTest extends TestCase
{
    use RefreshDatabase;

    public function test_validates_uuid_rules(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_validates_answer_type_enum(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }\n\n    public function test_toDto_mapping(): void
    {
        $this->markTestIncomplete('Test generated by execution script.');
    }
}
